#!/usr/bin/with-contenv sh

cd /app

if [ -z "$SEED" ]; then
    SEED='12345567890'
fi

if [ -z "$COUNT" ]; then
    COUNT='-1'
fi

if [ -z "$STEP" ]; then
    STEP='0'
fi

exec python run.py "$SEED" "$COUNT" "$STEP"
